name: "tdc-bumpversion-action"
description: "Semantic version increments of git tags."
inputs:
  gitEmail:
    required: true
  gitName:
    required: true
  incrementType:
    required: true
runs:
  using: docker
  image: "Dockerfile"
  args:
    - -gitEmail=${{ inputs.gitEmail }}
    - -gitName=${{ inputs.gitName }}
    - -incrementType=${{ inputs.incrementType }}
