on:
  workflow_dispatch:

jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --tags
      - name: bumpversion
        uses: ./
        id: bumpversion
        with:
          context: .
          gitEmail: sarusethi@rocketmail.com
          gitName: Gurleen Sethi
          incrementType: minor
